texture "1.traw" a1
texture "2.traw" a2
texture "3.traw" a3
texture "4.traw" a4
texture "5.traw" a5
texture "6.traw" a6
texture "7.traw" a7
texture "8.traw" a8

animation main
tag _main
frame a1
sleep 60
frame a2
sleep 60
frame a3
sleep 60
frame a4
sleep 60
frame a5
sleep 60
frame a6
sleep 60
frame a7
sleep 60
frame a8
sleep 60

end

