texture "1.traw" a1
texture "2.traw" a2
texture "3.traw" a3
texture "4.traw" a4
texture "5.traw" a5
texture "6.traw" a6


animation main
frame a1
sleep 100
frame a2
sleep 100
frame a3
sleep 100
frame a4
sleep 100
frame a5
sleep 100
frame a6
sleep 100
end

